version: '2'

services:
  cart:
    image: acmeshop-cart:latest
    hostname: cart
    restart: always
    ports:
      - '5000:5000'
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    environment:
      - REDIS_HOST=reddb
      - REDIS_PORT=6379
      - AUTH_MODE=0
  reddb:
    image: bitnami/redis:latest
    hostname: reddb
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
